### ISSUE TITLE
toil_cnacs run fails with: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 327: ordinal not in range(128)

### ISSUE THREAD

**Issue by stephan-hutter** [papaemmelab/toil_cnacs#3]
* toil_cnacs version: 0.2.0
* Python version: 2.7
* Operating System: Debian 10

### Description

I have set up a CNACS run using 8 samples as a panel of normals.
BAM files come from panel sequencing and are mapped to the hg19 reference genome.

### What I Did

The shell script I used to run CNACS is attached.
[run_cnacs.sh.txt](https://github.com/papaemmelab/toil_cnacs/files/5910497/run_cnacs.sh.txt)

Setting up and finalizing the panel of normals worked without issue.
Calculations start out fine, but at some point the CN analysis crashes with this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/_toil_worker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 520, in main
    workerScript(jobStore, config, jobName, jobStoreID)
  File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 466, in workerScript
    w.write(f.read().encode('utf-8')) # TODO load file using a buffer
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 327: ordinal not in range(128)
```
I have also attached the toil_logs.txt file and the complete output that was streamed to the terminal. 
[toil_logs.txt](https://github.com/papaemmelab/toil_cnacs/files/5910499/toil_logs.txt)
[terminal.txt](https://github.com/papaemmelab/toil_cnacs/files/5910498/terminal.txt)

It would be nice, if you could point me towards fixing the error.

Cheers,
Stephan

**Comment by mflevine** [comment]
Hi Stephan,
I think this is an encoding issue and caused by Toil not the wrapper code. 
https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal
Could you try running `export LC_CTYPE=en_US.UTF-8` before executing the script. If this does not work we can consider changing the version of Toil.
Best,
Max

**Comment by stephan-hutter** [comment]
Hi Max,

thanks for the quick reply.

I tried setting the locale, but I received the same error message.
In fact, I ran the script inside a docker container using your `papaemmelab/docker-cnacs` image to ensure no other parameters were wrongly set. I even checked that both `LC_ALL` and `LC_CTYPE` were set to `en_US.UTF-8` before launching.

So the problem seems to lie somewhere else.

Cheers,
Stephan

**Comment by stephan-hutter** [comment]
I have done some more searching online and stumbled across this issue from another Github project which seems to have the exact same problem:
https://github.com/DataBiosphere/toil/issues/2793

From what I gather, it has to do with Toil's handling of reading log files.
I imagine this has changed between versions, so that it is broken now. 
I assume this is general problem and does not only affect our data alone.

So I think your suggestion of rolling back the version of Toil might be worth a try.
The version I am currently using is 3.18.0, the one in your docker image.

Would you have any suggestions for a specific earlier version?

Cheers,
Stephan

**Comment by stephan-hutter** [comment]
Hi Max,

I tried running the pipeline with an earlier version of Toil, so I rolled it back to version 3.15.0.

Unfortunately, it still crashes with the same error message. However, logging is much more verbose with this version and seems to give more information on which part of the code actually produced the crash.
Find the logs attached here: [toil_logs.txt](https://github.com/papaemmelab/toil_cnacs/files/5924552/toil_logs.txt)

Maybe this helps pinpoint the problem.

Cheers,
Stephan

**Comment by jsmedmar** [comment]
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 327: ordinal not in range(128)
```

There seems to be a thread on this in SO: https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal

What version of python2 are you running? 

you may want to change this line :

```python
# File "/usr/local/lib/python2.7/site-packages/toil/leader.py", line 87, in __init__
msg += fH.read()
```

for this:

```python
# File "/usr/local/lib/python2.7/site-packages/toil/leader.py", line 87, in __init__
msg += fH.read().decode('utf-8')
```

**Comment by jsmedmar** [comment]
Maybe try disabling toil logging?
