### ISSUE TITLE
generate pool error

### ISSUE THREAD

**Issue by MNiebuhr** [papaemmelab/toil_cnacs#8]
* toil_cnacs version: 0.2.0
* Python version: 2.7.18
* Operating System: Linux VirtualBox 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Description

I tried generating a pool of normals using 4 (2F, 2M) .bam files and received an error for each job

### What I Did

I ran generate pool using a python script (pretty sure this is not the problem):
```
import os


def generate_pool(pool_dir, bed, ref, samples):
 	command = [
		'toil_cnacs', 'generate_pool',
		os.path.join(pool_dir["in"], 'jobstore_generate_pool'),
		'--stats',
		'--writeLogs', os.path.join(pool_dir["log"], 'toil_logs'),
		'--logFile', os.path.join(pool_dir["log"], 'toil_logs.txt'),
		'--outdir', pool_dir["out"],
		'--probe_bed', bed,
		'--fasta', ref
	]

	# add samples to generate pool options
	for sample in samples:
		command.extend(['--pool_samp', sample['bam'], sample['gender']])
		
	# add final docker options
	command.extend(['--docker papaemmelab/docker-cnacs'])
    	command.extend(['--volumes /home /home'])

	# create and run command
	command_str = ' '.join(command)
	os.system(command_str)


if __name__ == "__main__":
	user = os.getlogin()
	# define file paths for input data
	pool_in = "/home/{}/Desktop/CNACS/pool/in".format(user)
	pool_out = "/home/{}/Desktop/CNACS/pool/out".format(user)
	pool_log = "/home/{}/Desktop/CNACS/pool/log".format(user)
	pool_bed = "/home/{}/Desktop/CNACS/pool/bed".format(user)
	pool_ref = "/home/{}/Desktop/CNACS/pool/hg19".format(user)
	pool_dir = {"in": pool_in, "out": pool_out, "log": pool_log}


	# load samples
	files = os.listdir(pool_in)
	samples = []
	for file_name in files:
		if file_name.endswith(".bam"):
			sample_name = os.path.splitext(file_name)[0]
			sample_path = os.path.join(pool_in, file_name)
			gender = sample_name.split("_")[1]
			samples.append({'bam': sample_path, 'gender': gender})

	bed_file = [file for file in os.listdir(pool_bed) if file.endswith(".bed")][0]
	bed = os.path.join(pool_bed, bed_file)
	
	ref_file = [file for file in os.listdir(pool_ref) if file.endswith(".fasta")][0]
	ref = os.path.join(pool_ref, ref_file)

	# generate pool
	generate_pool(pool_dir, bed, ref, samples)

```
then I received the following error message multiple times for different jobs (I provide only 1 here)
```
INFO:toil.leader:Job ended successfully: 'procbam' h/C/jobZHpzj6
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'procbam' h/C/jobZHpzj6
WARNING:toil.leader:h/C/jobZHpzj6    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:h/C/jobZHpzj6    INFO:toil:Running Toil version 3.18.0-84239d802248a5f4a220e762b3b8ce5cc92af0be.
WARNING:toil.leader:h/C/jobZHpzj6    WARNING:toil.resource:'JTRES_cc628e4dbb18189c17948d38e0e213ab' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:h/C/jobZHpzj6    Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/tmp
WARNING:toil.leader:h/C/jobZHpzj6    [Thu Feb 29 08:18:23 UTC 2024] picard.sam.markduplicates.MarkDuplicates INPUT=[/home/christina/Desktop/CNACS/pool/in/QCMY-AN4095316_M.bam] OUTPUT=/home/christina/Desktop/CNACS/pool/out/QCMY-AN4095316_M/tmp/org.bam METRICS_FILE=/home/christina/Desktop/CNACS/pool/out/QCMY-AN4095316_M/tmp/metrics.txt VALIDATION_STRINGENCY=SILENT MAX_RECORDS_IN_RAM=5000000    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
WARNING:toil.leader:h/C/jobZHpzj6    [Thu Feb 29 08:18:23 UTC 2024] Executing as root@92197208b86e on Linux 5.15.0-52-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_232-8u232-b09-1~deb9u1-b09; Picard version: 2.9.0-1-gf5b9f50-SNAPSHOT
WARNING:toil.leader:h/C/jobZHpzj6    INFO	2024-02-29 08:18:23	MarkDuplicates	Start of doWork freeMemory: 7220557928; totalMemory: 7265714176; maxMemory: 7265714176
WARNING:toil.leader:h/C/jobZHpzj6    INFO	2024-02-29 08:18:23	MarkDuplicates	Reading input file and constructing read end information.
WARNING:toil.leader:h/C/jobZHpzj6    INFO	2024-02-29 08:18:23	MarkDuplicates	Will retain up to 27945054 data points before spilling to disk.
WARNING:toil.leader:h/C/jobZHpzj6    [Thu Feb 29 08:18:27 UTC 2024] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.06 minutes.
WARNING:toil.leader:h/C/jobZHpzj6    Runtime.totalMemory()=7265714176
WARNING:toil.leader:h/C/jobZHpzj6    To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
WARNING:toil.leader:h/C/jobZHpzj6    Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  2: MN00358.351.000H3CGGJ.1:MN00358:351:000H3CGGJ:1:11103:18572:7862_ACATTATGTGCT
WARNING:toil.leader:h/C/jobZHpzj6    	at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:133)
WARNING:toil.leader:h/C/jobZHpzj6    	at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:471)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:222)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
WARNING:toil.leader:h/C/jobZHpzj6    
WARNING:toil.leader:h/C/jobZHpzj6    Traceback (most recent call last):
WARNING:toil.leader:h/C/jobZHpzj6      File "/home/christina/.local/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
WARNING:toil.leader:h/C/jobZHpzj6        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:h/C/jobZHpzj6      File "/home/christina/.local/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:h/C/jobZHpzj6        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:h/C/jobZHpzj6      File "/home/christina/.local/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:h/C/jobZHpzj6        return self.run(fileStore)
WARNING:toil.leader:h/C/jobZHpzj6      File "/home/christina/.local/lib/python2.7/site-packages/toil_cnacs/jobs.py", line 101, in run
WARNING:toil.leader:h/C/jobZHpzj6        constants.UTIL,
WARNING:toil.leader:h/C/jobZHpzj6      File "/home/christina/.local/lib/python2.7/site-packages/toil_container/jobs.py", line 124, in call
WARNING:toil.leader:h/C/jobZHpzj6        raise exceptions.SystemCallError(error)
WARNING:toil.leader:h/C/jobZHpzj6    SystemCallError: The following error was raised during the container system call: <class 'docker.errors.ContainerError'>: Command '['/home/christina/.local/lib/python2.7/site-packages/toil_cnacs/data/cnacs/subscript_target/proc_bam.sh', '/home/christina/Desktop/CNACS/pool/out', '/home/christina/Desktop/CNACS/pool/out/probe.bed', '/home/christina/Desktop/CNACS/pool/in/QCMY-AN4095316_M.bam', 'QCMY-AN4095316_M', '1000', '30', '/home/christina/.local/lib/python2.7/site-packages/toil_cnacs/data/cnacs', '/home/christina/.local/lib/python2.7/site-packages/toil_cnacs/data/cnacs/lib/utility.sh']' in image 'papaemmelab/docker-cnacs' returned non-zero exit status 1: Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/tmp
WARNING:toil.leader:h/C/jobZHpzj6    [Thu Feb 29 08:18:23 UTC 2024] picard.sam.markduplicates.MarkDuplicates INPUT=[/home/christina/Desktop/CNACS/pool/in/QCMY-AN4095316_M.bam] OUTPUT=/home/christina/Desktop/CNACS/pool/out/QCMY-AN4095316_M/tmp/org.bam METRICS_FILE=/home/christina/Desktop/CNACS/pool/out/QCMY-AN4095316_M/tmp/metrics.txt VALIDATION_STRINGENCY=SILENT MAX_RECORDS_IN_RAM=5000000    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
WARNING:toil.leader:h/C/jobZHpzj6    [Thu Feb 29 08:18:23 UTC 2024] Executing as root@92197208b86e on Linux 5.15.0-52-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_232-8u232-b09-1~deb9u1-b09; Picard version: 2.9.0-1-gf5b9f50-SNAPSHOT
WARNING:toil.leader:h/C/jobZHpzj6    INFO	2024-02-29 08:18:23	MarkDuplicates	Start of doWork freeMemory: 7220557928; totalMemory: 7265714176; maxMemory: 7265714176
WARNING:toil.leader:h/C/jobZHpzj6    INFO	2024-02-29 08:18:23	MarkDuplicates	Reading input file and constructing read end information.
WARNING:toil.leader:h/C/jobZHpzj6    INFO	2024-02-29 08:18:23	MarkDuplicates	Will retain up to 27945054 data points before spilling to disk.
WARNING:toil.leader:h/C/jobZHpzj6    [Thu Feb 29 08:18:27 UTC 2024] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.06 minutes.
WARNING:toil.leader:h/C/jobZHpzj6    Runtime.totalMemory()=7265714176
WARNING:toil.leader:h/C/jobZHpzj6    To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
WARNING:toil.leader:h/C/jobZHpzj6    Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  2: MN00358.351.000H3CGGJ.1:MN00358:351:000H3CGGJ:1:11103:18572:7862_ACATTATGTGCT
WARNING:toil.leader:h/C/jobZHpzj6    	at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:133)
WARNING:toil.leader:h/C/jobZHpzj6    	at htsjdk.samtools.CoordinateSortedPairInfoMap.remove(CoordinateSortedPairInfoMap.java:86)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.remove(DiskBasedReadEndsForMarkDuplicatesMap.java:61)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:471)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:222)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
WARNING:toil.leader:h/C/jobZHpzj6    	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
WARNING:toil.leader:h/C/jobZHpzj6    
WARNING:toil.leader:h/C/jobZHpzj6    ERROR:toil.worker:Exiting the worker because of a failed job on host christina-VirtualBox
WARNING:toil.leader:h/C/jobZHpzj6    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'procbam' h/C/jobZHpzj6 with ID h/C/jobZHpzj6 to 0
WARNING:toil.leader:h/C/jobZHpzj6    /home/christina/Desktop/CNACS/pool/out/QCMY-AN4095316_M/tmp exists.
WARNING:toil.leader:h/C/jobZHpzj6    java MarkDuplicates.jar
WARNING:toil.leader:h/C/jobZHpzj6    
WARNING:toil.leader:Job 'procbam' h/C/jobZHpzj6 with ID h/C/jobZHpzj6 is completely failed

```

Do you have any ideas on how I could try to fix this problem?

Thanks a lot!
Marco Niebuhr

**Comment by juanesarango** [comment]
Hi Marco, 

The error suggests an issue with your bam. Seems like there's some potential duplicates that make `Picard MarkDuplicates` step to fail. 
I wouldn't know specifically what you should fix, but you should explore things like: 
- Sort the bam
- Run `samtools quickcheck -v your.bam`
- Run `picard ValidateSamFile`

Hope it helps, 

Juanes
